[desired_force]
factor = 1.0
goal_threshold = 0.2
relaxation_time = 0.5

[social_force]
factor = 5.1
lambda_importance = 2.0
gamma = 0.35
n = 2
n_prime = 3

[obstacle_force]
factor = 10.0
sigma = 0.2

[group_coherence_force]
factor = 3.0
